{
  "hash": "19253beb40ed975770a01e26453a9ed0",
  "result": {
    "markdown": "---\ntitle: \"Statistics Basics\"\nabstract: \"Statistical tests, Statistics, Statistic, CLT, etc.\"\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 10, fig.height = 6)\nlibrary(tidyverse)\nlibrary(car)\nlibrary(emmeans)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(patchwork)\nlibrary(corrplot)\n\n# Helper function for separators\nsep_line <- function(char = \"=\", n = 50) {\n  cat(paste(rep(char, n), collapse = \"\"), \"\\n\")\n}\n```\n:::\n\n\n\n# Part 1: The Coffee Shop Example - Why ANOVA Types Matter\n\n## Setting the Stage with a Simple Story\n\nImagine you own a coffee shop and want to understand what affects customer satisfaction scores (1-10 scale). You consider two factors:\n\n1. **Coffee Type**: Regular vs Decaf\n2. **Time of Day**: Morning vs Afternoon\n\nLet's create this scenario with data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Create a BALANCED design first (equal sample sizes)\nn_per_cell <- 20  # 20 customers in each combination\n\nbalanced_coffee <- expand.grid(\n  coffee_type = c(\"Regular\", \"Decaf\"),\n  time_of_day = c(\"Morning\", \"Afternoon\"),\n  replicate = 1:n_per_cell\n) %>%\n  mutate(\n    # Create satisfaction scores with main effects and interaction\n    satisfaction = case_when(\n      coffee_type == \"Regular\" & time_of_day == \"Morning\" ~ rnorm(n(), 8, 1),    # High satisfaction\n      coffee_type == \"Regular\" & time_of_day == \"Afternoon\" ~ rnorm(n(), 6, 1),  # Medium\n      coffee_type == \"Decaf\" & time_of_day == \"Morning\" ~ rnorm(n(), 5, 1),      # Low-medium\n      coffee_type == \"Decaf\" & time_of_day == \"Afternoon\" ~ rnorm(n(), 7, 1)     # Medium-high\n    ),\n    coffee_type = factor(coffee_type),\n    time_of_day = factor(time_of_day)\n  ) %>%\n  select(-replicate)\n\n# Show the structure\nprint(\"Balanced Design - Sample Sizes:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Balanced Design - Sample Sizes:\"\n```\n:::\n\n```{.r .cell-code}\ntable(balanced_coffee$coffee_type, balanced_coffee$time_of_day)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n         \n          Morning Afternoon\n  Regular      20        20\n  Decaf        20        20\n```\n:::\n\n```{.r .cell-code}\n# Calculate means for each cell\ncell_means_balanced <- balanced_coffee %>%\n  group_by(coffee_type, time_of_day) %>%\n  summarise(\n    mean_satisfaction = mean(satisfaction),\n    n = n(),\n    .groups = 'drop'\n  )\n\nkable(cell_means_balanced, digits = 2, \n      caption = \"Mean Satisfaction Scores - Balanced Design\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{llrr}\n\\caption{\\label{tab:create-coffee-data}Mean Satisfaction Scores - Balanced Design}\\\\\n\\toprule\ncoffee\\_type & time\\_of\\_day & mean\\_satisfaction & n\\\\\n\\midrule\nRegular & Morning & 8.31 & 20\\\\\nRegular & Afternoon & 5.74 & 20\\\\\nDecaf & Morning & 5.00 & 20\\\\\nDecaf & Afternoon & 7.01 & 20\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n## Now Let's Create Reality: Unbalanced Data\n\nIn real life, you don't get equal numbers of customers in each category. Maybe fewer people order decaf in the morning:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create UNBALANCED design (unequal sample sizes)\nset.seed(42)\n\nunbalanced_coffee <- bind_rows(\n  # Regular + Morning: 30 customers (popular!)\n  data.frame(\n    coffee_type = \"Regular\",\n    time_of_day = \"Morning\",\n    satisfaction = rnorm(30, 8, 1)\n  ),\n  # Regular + Afternoon: 25 customers\n  data.frame(\n    coffee_type = \"Regular\",\n    time_of_day = \"Afternoon\",\n    satisfaction = rnorm(25, 6, 1)\n  ),\n  # Decaf + Morning: 10 customers (unpopular combination)\n  data.frame(\n    coffee_type = \"Decaf\",\n    time_of_day = \"Morning\",\n    satisfaction = rnorm(10, 5, 1)\n  ),\n  # Decaf + Afternoon: 20 customers\n  data.frame(\n    coffee_type = \"Decaf\",\n    time_of_day = \"Afternoon\",\n    satisfaction = rnorm(20, 7, 1)\n  )\n) %>%\n  mutate(\n    coffee_type = factor(coffee_type),\n    time_of_day = factor(time_of_day)\n  )\n\nprint(\"Unbalanced Design - Sample Sizes:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Unbalanced Design - Sample Sizes:\"\n```\n:::\n\n```{.r .cell-code}\ntable(unbalanced_coffee$coffee_type, unbalanced_coffee$time_of_day)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n         \n          Afternoon Morning\n  Decaf          20      10\n  Regular        25      30\n```\n:::\n\n```{.r .cell-code}\ncell_means_unbalanced <- unbalanced_coffee %>%\n  group_by(coffee_type, time_of_day) %>%\n  summarise(\n    mean_satisfaction = mean(satisfaction),\n    n = n(),\n    .groups = 'drop'\n  )\n\nkable(cell_means_unbalanced, digits = 2,\n      caption = \"Mean Satisfaction Scores - Unbalanced Design\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{llrr}\n\\caption{\\label{tab:create-unbalanced-data}Mean Satisfaction Scores - Unbalanced Design}\\\\\n\\toprule\ncoffee\\_type & time\\_of\\_day & mean\\_satisfaction & n\\\\\n\\midrule\nDecaf & Afternoon & 7.13 & 20\\\\\nDecaf & Morning & 4.94 & 10\\\\\nRegular & Afternoon & 5.92 & 25\\\\\nRegular & Morning & 8.07 & 30\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Part 2: The Mathematical Foundation of ANOVA\n\n## The General Linear Model\n\nANOVA is actually a special case of linear regression. Our two-way ANOVA model can be written as:\n\n$$Y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\epsilon_{ijk}$$\n\nWhere:\n\n* $Y_{ijk}$ = satisfaction score for the $k$-th customer with coffee type $i$ and time $j$\n* $\\mu$ = grand mean (overall average satisfaction)\n* $\\alpha_i$ = main effect of coffee type $i$ (how much Regular or Decaf changes satisfaction)\n* $\\beta_j$ = main effect of time of day $j$ (how much Morning or Afternoon changes satisfaction)\n* $(\\alpha\\beta)_{ij}$ = interaction effect (does the coffee type effect depend on time of day?)\n* $\\epsilon_{ijk}$ = random error (individual differences)\n\n## Sum of Squares Decomposition\n\nThe total variation in our data can be decomposed:\n\n$$SS_{Total} = SS_{CoffeeType} + SS_{Time} + SS_{Interaction} + SS_{Error}$$\n\nIn plain English: \nTotal variation = Variation due to coffee type + Variation due to time + Variation due to their combination + Random variation\n\n# Part 3: Why Order Matters - A Visual Explanation\n\n## Understanding Sequential vs Simultaneous Testing\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a visual demonstration of why order matters\nset.seed(123)\n\n# Function to calculate partial correlations and visualize\ndemonstrate_order_effects <- function(data) {\n  # Calculate total sum of squares\n  grand_mean <- mean(data$satisfaction)\n  ss_total <- sum((data$satisfaction - grand_mean)^2)\n  \n  # Calculate group means\n  coffee_means <- tapply(data$satisfaction, data$coffee_type, mean)\n  time_means <- tapply(data$satisfaction, data$time_of_day, mean)\n  \n  # Calculate marginal sums of squares (ignoring the other factor)\n  ss_coffee_alone <- sum(table(data$coffee_type) * (coffee_means - grand_mean)^2)\n  ss_time_alone <- sum(table(data$time_of_day) * (time_means - grand_mean)^2)\n  \n  # Create a data frame for visualization\n  results <- data.frame(\n    Approach = c(\"Coffee First\", \"Time First\", \"Coffee Alone\", \"Time Alone\"),\n    Coffee_SS = c(ss_coffee_alone, NA, ss_coffee_alone, NA),\n    Time_SS = c(NA, ss_time_alone, NA, ss_time_alone),\n    Order = c(\"1st\", \"1st\", \"Marginal\", \"Marginal\")\n  )\n  \n  return(list(\n    ss_total = ss_total,\n    ss_coffee_alone = ss_coffee_alone,\n    ss_time_alone = ss_time_alone,\n    coffee_means = coffee_means,\n    time_means = time_means,\n    grand_mean = grand_mean\n  ))\n}\n\n# Apply to both datasets\nbalanced_results <- demonstrate_order_effects(balanced_coffee)\nunbalanced_results <- demonstrate_order_effects(unbalanced_coffee)\n\n# Create comparison table\ncomparison_df <- data.frame(\n  Design = c(\"Balanced\", \"Balanced\", \"Unbalanced\", \"Unbalanced\"),\n  Factor = c(\"Coffee Type\", \"Time of Day\", \"Coffee Type\", \"Time of Day\"),\n  `SS When Tested First` = c(\n    balanced_results$ss_coffee_alone,\n    balanced_results$ss_time_alone,\n    unbalanced_results$ss_coffee_alone,\n    unbalanced_results$ss_time_alone\n  ),\n  check.names = FALSE\n)\n\nkable(comparison_df, digits = 2, \n      caption = \"Sum of Squares When Each Factor is Tested First\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{llr}\n\\caption{\\label{tab:order-matters-demo}Sum of Squares When Each Factor is Tested First}\\\\\n\\toprule\nDesign & Factor & SS When Tested First\\\\\n\\midrule\nBalanced & Coffee Type & 21.03\\\\\nBalanced & Time of Day & 1.60\\\\\nUnbalanced & Coffee Type & 9.21\\\\\nUnbalanced & Time of Day & 14.48\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n::::{.callout-note}\n## Why Does Order Matter in Unbalanced Designs?\n\nIn unbalanced designs, the factors are **correlated**. When factors are correlated:\n\n1. The effect of Coffee Type partially overlaps with the effect of Time\n2. Testing Coffee first \"claims\" the overlapping variance\n3. Testing Time first would claim that same overlapping variance differently\n4. This is why Type I (sequential) ANOVA gives different results based on order\n::::\n\n# Part 4: The Controversy - Types I, II, and III Sum of Squares\n\n## Manual Calculation Tables for Understanding\n\nLet's manually calculate the different types of sum of squares to truly understand what's happening:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to manually calculate all types of SS\ncalculate_all_ss_types <- function(data, show_details = TRUE) {\n  # Prepare data\n  n <- nrow(data)\n  grand_mean <- mean(data$satisfaction)\n  \n  # Get cell means and counts\n  cell_summary <- data %>%\n    group_by(coffee_type, time_of_day) %>%\n    summarise(\n      mean = mean(satisfaction),\n      n = n(),\n      sum = sum(satisfaction),\n      .groups = 'drop'\n    )\n  \n  # Marginal means\n  coffee_marginal <- data %>%\n    group_by(coffee_type) %>%\n    summarise(\n      mean = mean(satisfaction),\n      n = n(),\n      .groups = 'drop'\n    )\n  \n  time_marginal <- data %>%\n    group_by(time_of_day) %>%\n    summarise(\n      mean = mean(satisfaction),\n      n = n(),\n      .groups = 'drop'\n    )\n  \n  if(show_details) {\n    print(\"Cell Means and Sample Sizes:\")\n    print(cell_summary)\n    print(\"\")\n    print(\"Marginal Means - Coffee Type:\")\n    print(coffee_marginal)\n    print(\"\")\n    print(\"Marginal Means - Time of Day:\")\n    print(time_marginal)\n    print(\"\")\n    print(paste(\"Grand Mean:\", round(grand_mean, 3)))\n    sep_line(\"-\", 40)\n  }\n  \n  # Calculate Type I SS (Sequential)\n  # Order 1: Coffee -> Time -> Interaction\n  \n  # SS(Coffee | μ)\n  ss_coffee_type1 <- sum(coffee_marginal$n * (coffee_marginal$mean - grand_mean)^2)\n  \n  # For SS(Time | μ, Coffee), we need residuals after fitting Coffee\n  model_coffee_only <- lm(satisfaction ~ coffee_type, data = data)\n  residuals_after_coffee <- residuals(model_coffee_only)\n  \n  # Create pseudo-data with residuals\n  pseudo_data_time <- data.frame(\n    residuals = residuals_after_coffee,\n    time_of_day = data$time_of_day\n  )\n  \n  model_time_on_residuals <- lm(residuals ~ time_of_day, data = pseudo_data_time)\n  ss_time_type1 <- sum((fitted(model_time_on_residuals))^2)\n  \n  # Calculate Type II SS (Marginal, no interaction)\n  model_both_main <- lm(satisfaction ~ coffee_type + time_of_day, data = data)\n  model_coffee_only <- lm(satisfaction ~ coffee_type, data = data)\n  model_time_only <- lm(satisfaction ~ time_of_day, data = data)\n  \n  ss_coffee_type2 <- sum((fitted(model_both_main) - fitted(model_time_only))^2)\n  ss_time_type2 <- sum((fitted(model_both_main) - fitted(model_coffee_only))^2)\n  \n  # Calculate Type III SS (Marginal, with interaction)\n  # This requires more complex calculations with contrast coding\n  \n  # Create results table\n  results <- data.frame(\n    `Type` = c(\"Type I\", \"Type II\", \"Type III*\"),\n    `SS_Coffee` = c(ss_coffee_type1, ss_coffee_type2, NA),\n    `SS_Time` = c(ss_time_type1, ss_time_type2, NA),\n    check.names = FALSE\n  )\n  \n  return(results)\n}\n\n# Calculate for both designs\nprint(\"BALANCED DESIGN:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"BALANCED DESIGN:\"\n```\n:::\n\n```{.r .cell-code}\nbalanced_calc <- calculate_all_ss_types(balanced_coffee, show_details = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Cell Means and Sample Sizes:\"\n# A tibble: 4 x 5\n  coffee_type time_of_day  mean     n   sum\n  <fct>       <fct>       <dbl> <int> <dbl>\n1 Regular     Morning      8.31    20  166.\n2 Regular     Afternoon    5.74    20  115.\n3 Decaf       Morning      5.00    20  100.\n4 Decaf       Afternoon    7.01    20  140.\n[1] \"\"\n[1] \"Marginal Means - Coffee Type:\"\n# A tibble: 2 x 3\n  coffee_type  mean     n\n  <fct>       <dbl> <int>\n1 Regular      7.03    40\n2 Decaf        6.00    40\n[1] \"\"\n[1] \"Marginal Means - Time of Day:\"\n# A tibble: 2 x 3\n  time_of_day  mean     n\n  <fct>       <dbl> <int>\n1 Morning      6.66    40\n2 Afternoon    6.37    40\n[1] \"\"\n[1] \"Grand Mean: 6.516\"\n---------------------------------------- \n```\n:::\n\n```{.r .cell-code}\nkable(balanced_calc, digits = 2, \n      caption = \"Manual SS Calculations - Balanced Design\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{lrr}\n\\caption{\\label{tab:manual-calculations}Manual SS Calculations - Balanced Design}\\\\\n\\toprule\nType & SS\\_Coffee & SS\\_Time\\\\\n\\midrule\nType I & 21.03 & 1.6\\\\\nType II & 21.03 & 1.6\\\\\nType III* & NA & NA\\\\\n\\bottomrule\n\\end{longtable}\n:::\n\n```{.r .cell-code}\nprint(\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"\"\n```\n:::\n\n```{.r .cell-code}\nprint(\"UNBALANCED DESIGN:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"UNBALANCED DESIGN:\"\n```\n:::\n\n```{.r .cell-code}\nunbalanced_calc <- calculate_all_ss_types(unbalanced_coffee, show_details = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Cell Means and Sample Sizes:\"\n# A tibble: 4 x 5\n  coffee_type time_of_day  mean     n   sum\n  <fct>       <fct>       <dbl> <int> <dbl>\n1 Decaf       Afternoon    7.13    20 143. \n2 Decaf       Morning      4.94    10  49.4\n3 Regular     Afternoon    5.92    25 148. \n4 Regular     Morning      8.07    30 242. \n[1] \"\"\n[1] \"Marginal Means - Coffee Type:\"\n# A tibble: 2 x 3\n  coffee_type  mean     n\n  <fct>       <dbl> <int>\n1 Decaf        6.40    30\n2 Regular      7.09    55\n[1] \"\"\n[1] \"Marginal Means - Time of Day:\"\n# A tibble: 2 x 3\n  time_of_day  mean     n\n  <fct>       <dbl> <int>\n1 Afternoon    6.46    45\n2 Morning      7.29    40\n[1] \"\"\n[1] \"Grand Mean: 6.849\"\n---------------------------------------- \n```\n:::\n\n```{.r .cell-code}\nkable(unbalanced_calc, digits = 2,\n      caption = \"Manual SS Calculations - Unbalanced Design\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{lrr}\n\\caption{\\label{tab:manual-calculations}Manual SS Calculations - Unbalanced Design}\\\\\n\\toprule\nType & SS\\_Coffee & SS\\_Time\\\\\n\\midrule\nType I & 9.21 & 10.17\\\\\nType II & 5.34 & 10.61\\\\\nType III* & NA & NA\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n## Type I Sum of Squares (Sequential)\n\n**Mathematical Definition:**\n\n* $SS(\\alpha | \\mu)$ = Sum of squares for A after fitting the mean\n* $SS(\\beta | \\mu, \\alpha)$ = Sum of squares for B after fitting mean and A\n* $SS(\\alpha\\beta | \\mu, \\alpha, \\beta)$ = Sum of squares for interaction after fitting everything else\n\n**Plain English:** Type I asks \"What does each factor explain that wasn't already explained by factors entered before it?\"\n\n::::{.callout-info}\n## Example: When Type I Makes Sense\n\n**Scenario: Educational Achievement Study**\n\nImagine studying factors affecting student test scores where we have a clear causal hierarchy:\n\n1. **Socioeconomic Status (SES)** - This is a background variable that exists before schooling\n2. **School Quality** - Students are assigned to schools based partly on where they live (related to SES)\n3. **Teaching Method** - Applied within schools\n\nHere, it makes sense to use Type I with SES entered first, then School Quality, then Teaching Method. We want to know:\n\n* How much variance does SES explain?\n* How much *additional* variance does School Quality explain after accounting for SES?\n* How much *additional* variance does Teaching Method explain after accounting for both?\n\nThis sequential approach respects the causal/temporal ordering of these factors.\n::::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type I implementation with detailed output\nprint(\"TYPE I - Sequential Sum of Squares\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"TYPE I - Sequential Sum of Squares\"\n```\n:::\n\n```{.r .cell-code}\nsep_line(\"=\", 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n================================================== \n```\n:::\n\n```{.r .cell-code}\nmodel_type1 <- lm(satisfaction ~ coffee_type + time_of_day + coffee_type:time_of_day, \n                  data = unbalanced_coffee)\nanova_type1 <- anova(model_type1)\nprint(anova_type1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\nAnalysis of Variance Table\n\nResponse: satisfaction\n                        Df Sum Sq Mean Sq F value    Pr(>F)    \ncoffee_type              1  9.214   9.214  7.9036  0.006186 ** \ntime_of_day              1 10.607  10.607  9.0985  0.003417 ** \ncoffee_type:time_of_day  1 84.400  84.400 72.3995 7.439e-13 ***\nResiduals               81 94.426   1.166                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n::::{.callout-question}\n## What Does Each Row Mean?\n\nClick below to understand each row in the ANOVA table:\n\n<details>\n<summary>**Click to see explanation**</summary>\n\n**Row 1 - coffee_type:** \nThis shows the sum of squares for coffee type when it's the FIRST factor considered (after the intercept). It answers: \"How much variance in satisfaction is explained by coffee type alone?\"\n\n**Row 2 - time_of_day:**\nThis shows the sum of squares for time of day AFTER removing the effect of coffee type. It answers: \"How much additional variance is explained by time of day that wasn't already explained by coffee type?\"\n\n**Row 3 - coffee_type:time_of_day:**\nThis is the interaction term. It answers: \"Is the effect of coffee type different at different times of day?\" A significant interaction means the effect of one factor depends on the level of the other.\n\n**Row 4 - Residuals:**\nThis is the unexplained variance - the variation in satisfaction scores that can't be explained by any of our factors. It represents individual differences and measurement error.\n\n**Columns Explained:**\n\n* **Df (Degrees of Freedom):** Number of independent pieces of information. For factors: (number of levels - 1)\n* **Sum Sq:** Total squared deviations explained by that factor\n* **Mean Sq:** Sum Sq divided by Df (average squared deviation)\n* **F value:** Ratio of factor's Mean Sq to Residual Mean Sq (signal-to-noise ratio)\n* **Pr(>F):** p-value - probability of seeing this F-value or larger if null hypothesis is true\n</details>\n::::\n\n## Type II Sum of Squares (Hierarchical)\n\n**Mathematical Definition:**\n\n* $SS(\\alpha | \\mu, \\beta)$ = Sum of squares for A after fitting mean and B\n* $SS(\\beta | \\mu, \\alpha)$ = Sum of squares for B after fitting mean and A\n* $SS(\\alpha\\beta | \\mu, \\alpha, \\beta)$ = Sum of squares for interaction after main effects\n\n**Plain English:** Type II asks \"What does each main effect explain that the other main effect doesn't, ignoring interactions?\"\n\n**When to use:** When you want to test main effects assuming no interaction (most common in practice)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(\"TYPE II - Hierarchical Sum of Squares\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"TYPE II - Hierarchical Sum of Squares\"\n```\n:::\n\n```{.r .cell-code}\nsep_line(\"=\", 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n================================================== \n```\n:::\n\n```{.r .cell-code}\nAnova(model_type1, type = \"II\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\nAnova Table (Type II tests)\n\nResponse: satisfaction\n                        Sum Sq Df F value    Pr(>F)    \ncoffee_type              5.339  1  4.5802  0.035352 *  \ntime_of_day             10.607  1  9.0985  0.003417 ** \ncoffee_type:time_of_day 84.400  1 72.3995 7.439e-13 ***\nResiduals               94.426 81                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n::::{.callout-question}\n## What Does Each Row Mean in Type II?\n\n<details>\n<summary>**Click to see explanation**</summary>\n\n**Key Differences from Type I:**\n\n**Row 1 - coffee_type:**\nNow shows SS for coffee type AFTER adjusting for time_of_day (but NOT interaction). It answers: \"What unique variance does coffee type explain that time doesn't?\"\n\n**Row 2 - time_of_day:**\nShows SS for time AFTER adjusting for coffee_type (but NOT interaction). It answers: \"What unique variance does time explain that coffee type doesn't?\"\n\n**Row 3 - coffee_type:time_of_day:**\nSame as Type I - interaction is always tested last.\n\n**Why Type II is Often Preferred:**\n\n* Tests each main effect controlling for other main effects\n* Order doesn't matter (unlike Type I)\n* Assumes no interaction when testing main effects\n* More balanced approach for most research questions\n</details>\n::::\n\n## Type III Sum of Squares (Marginal)\n\n**Mathematical Definition:**\n\n* $SS(\\alpha | \\mu, \\beta, \\alpha\\beta)$ = Sum of squares for A after fitting everything else\n* $SS(\\beta | \\mu, \\alpha, \\alpha\\beta)$ = Sum of squares for B after fitting everything else\n* $SS(\\alpha\\beta | \\mu, \\alpha, \\beta)$ = Sum of squares for interaction after main effects\n\n**Plain English:** Type III asks \"What does each effect explain that isn't explained by any other effect, including interactions?\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type III implementation\n# IMPORTANT: Must use sum-to-zero contrasts for Type III\ncontrasts(unbalanced_coffee$coffee_type) <- contr.sum(2)\ncontrasts(unbalanced_coffee$time_of_day) <- contr.sum(2)\n\nmodel_type3 <- lm(satisfaction ~ coffee_type * time_of_day, data = unbalanced_coffee)\n\nprint(\"TYPE III - Marginal Sum of Squares\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"TYPE III - Marginal Sum of Squares\"\n```\n:::\n\n```{.r .cell-code}\nsep_line(\"=\", 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n================================================== \n```\n:::\n\n```{.r .cell-code}\nAnova(model_type3, type = \"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\nAnova Table (Type III tests)\n\nResponse: satisfaction\n                         Sum Sq Df   F value    Pr(>F)    \n(Intercept)             3041.77  1 2609.2756 < 2.2e-16 ***\ncoffee_type               16.40  1   14.0657 0.0003302 ***\ntime_of_day                0.01  1    0.0077 0.9302036    \ncoffee_type:time_of_day   84.40  1   72.3995 7.439e-13 ***\nResiduals                 94.43 81                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\n::::{.callout-question}\n## What Does Each Row Mean in Type III?\n\n<details>\n<summary>**Click to see explanation**</summary>\n\n**Type III Special Characteristics:**\n\n**Row 1 - (Intercept):**\nType III includes the intercept test, which tests if the grand mean equals zero (usually not interesting).\n\n**Row 2 - coffee_type:**\nTests coffee type AFTER adjusting for time AND interaction. Answers: \"Is there a coffee type effect averaged across all times?\"\n\n**Row 3 - time_of_day:**\nTests time AFTER adjusting for coffee type AND interaction. Answers: \"Is there a time effect averaged across all coffee types?\"\n\n**Row 4 - coffee_type:time_of_day:**\nSame as other types - interaction effect.\n\n**When Type III is Useful:**\n\n* When interaction is significant\n* When you want the most conservative test\n* When following certain field conventions (e.g., some areas of psychology)\n* Tests \"average\" effects across all levels of other factors\n</details>\n::::\n\n# Part 5: Why All Three Types Give the Same Answer for Balanced Data\n\n## The Magic of Orthogonality\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Demonstrate orthogonality in balanced vs unbalanced designs\n\ncheck_orthogonality <- function(data, title) {\n  # Create design matrix\n  X <- model.matrix(~ coffee_type * time_of_day, data = data)\n  \n  # Calculate correlation matrix (excluding intercept)\n  cor_matrix <- cor(X[, -1])\n  \n  # Visualize\n  par(mar = c(5, 4, 4, 2))\n  corrplot(cor_matrix, \n           method = \"color\", \n           type = \"upper\",\n           tl.cex = 0.8,\n           tl.col = \"black\",\n           title = title,\n           mar = c(0, 0, 2, 0),\n           addCoef.col = \"black\",\n           number.cex = 0.8)\n  \n  return(cor_matrix)\n}\n\n# Check both designs\npar(mfrow = c(1, 2))\nbalanced_cors <- check_orthogonality(balanced_coffee, \n                                     \"Balanced Design\\n(Orthogonal)\")\nunbalanced_cors <- check_orthogonality(unbalanced_coffee, \n                                       \"Unbalanced Design\\n(Non-orthogonal)\")\n```\n\n::: {.cell-output-display}\n![](stat_files/figure-pdf/why-balanced-same-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::::{.callout-important}\n## Why Balanced Designs Make All Types Equal\n\nIn balanced designs, the design vectors are **orthogonal** (uncorrelated):\n\n1. **Zero Correlation:** The correlation between coffee_type and time_of_day is 0\n2. **No Overlapping Variance:** Each factor explains completely separate portions of variance\n3. **Order Doesn't Matter:** Since factors don't overlap, the sequence of testing is irrelevant\n4. **Unique Contributions:** Each factor's contribution is unique and doesn't depend on others\n\nThis is why balanced designs are so desirable in experimental research!\n::::\n\n## Detailed Comparison Table\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a comprehensive comparison\ncompare_ss_types <- function(data, design_name) {\n  # Type I (two orders)\n  model_i_order1 <- lm(satisfaction ~ coffee_type + time_of_day, data = data)\n  model_i_order2 <- lm(satisfaction ~ time_of_day + coffee_type, data = data)\n  \n  type_i_order1 <- anova(model_i_order1)\n  type_i_order2 <- anova(model_i_order2)\n  \n  # Type II\n  type_ii <- Anova(model_i_order1, type = \"II\")\n  \n  # Type III (with proper contrasts)\n  data_copy <- data\n  contrasts(data_copy$coffee_type) <- contr.sum(2)\n  contrasts(data_copy$time_of_day) <- contr.sum(2)\n  model_iii <- lm(satisfaction ~ coffee_type + time_of_day, data = data_copy)\n  type_iii <- Anova(model_iii, type = \"III\")\n  \n  # Create comparison table\n  comparison <- data.frame(\n    Design = design_name,\n    Type = c(\"I (Coffee→Time)\", \"I (Time→Coffee)\", \"II\", \"III\"),\n    Coffee_SS = c(\n      type_i_order1$`Sum Sq`[1],\n      type_i_order2$`Sum Sq`[2],\n      type_ii$`Sum Sq`[1],\n      type_iii$`Sum Sq`[2]\n    ),\n    Time_SS = c(\n      type_i_order1$`Sum Sq`[2],\n      type_i_order2$`Sum Sq`[1],\n      type_ii$`Sum Sq`[2],\n      type_iii$`Sum Sq`[3]\n    )\n  )\n  \n  return(comparison)\n}\n\n# Compare both designs\nbalanced_comparison <- compare_ss_types(balanced_coffee, \"Balanced\")\nunbalanced_comparison <- compare_ss_types(unbalanced_coffee, \"Unbalanced\")\n\nfull_comparison <- rbind(balanced_comparison, unbalanced_comparison)\n\nkable(full_comparison, digits = 2,\n      caption = \"Sum of Squares Comparison: All Types, Both Designs\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  pack_rows(\"Balanced Design\", 1, 4) %>%\n  pack_rows(\"Unbalanced Design\", 5, 8)\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{llrr}\n\\caption{\\label{tab:detailed-comparison}Sum of Squares Comparison: All Types, Both Designs}\\\\\n\\toprule\nDesign & Type & Coffee\\_SS & Time\\_SS\\\\\n\\midrule\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\textbf{Balanced Design}}\\\\\n\\hspace{1em}Balanced & I (Coffee→Time) & 21.03 & 1.60\\\\\n\\hspace{1em}Balanced & I (Time→Coffee) & 21.03 & 1.60\\\\\n\\hspace{1em}Balanced & II & 21.03 & 1.60\\\\\n\\hspace{1em}Balanced & III & 21.03 & 1.60\\\\\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\textbf{Unbalanced Design}}\\\\\n\\hspace{1em}Unbalanced & I (Coffee→Time) & 9.21 & 10.61\\\\\n\\hspace{1em}Unbalanced & I (Time→Coffee) & 5.34 & 14.48\\\\\n\\hspace{1em}Unbalanced & II & 5.34 & 10.61\\\\\n\\hspace{1em}Unbalanced & III & 5.34 & 10.61\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Part 6: Variance Heterogeneity (Unequal Variances)\n\n## Creating Data with Unequal Variances\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Create data with very different variances\nhetero_data <- bind_rows(\n  data.frame(\n    group = \"A\",\n    value = rnorm(30, mean = 50, sd = 2)  # Small variance\n  ),\n  data.frame(\n    group = \"B\", \n    value = rnorm(30, mean = 52, sd = 8)  # Medium variance\n  ),\n  data.frame(\n    group = \"C\",\n    value = rnorm(30, mean = 54, sd = 15) # Large variance\n  )\n) %>%\n  mutate(group = factor(group))\n\n# Calculate actual variances\nvariance_summary <- hetero_data %>%\n  group_by(group) %>%\n  summarise(\n    Mean = mean(value),\n    Variance = var(value),\n    SD = sd(value),\n    n = n(),\n    .groups = 'drop'\n  )\n\nkable(variance_summary, digits = 2,\n      caption = \"Group Statistics with Heterogeneous Variances\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{lrrrr}\n\\caption{\\label{tab:variance-heterogeneity}Group Statistics with Heterogeneous Variances}\\\\\n\\toprule\ngroup & Mean & Variance & SD & n\\\\\n\\midrule\nA & 49.91 & 3.85 & 1.96 & 30\\\\\nB & 53.43 & 44.64 & 6.68 & 30\\\\\nC & 54.37 & 170.22 & 13.05 & 30\\\\\n\\bottomrule\n\\end{longtable}\n:::\n\n```{.r .cell-code}\n# Visualize the different variances\np1 <- ggplot(hetero_data, aes(x = group, y = value, fill = group)) +\n  geom_boxplot(alpha = 0.7) +\n  geom_point(position = position_jitter(width = 0.1), alpha = 0.3) +\n  labs(title = \"Heterogeneous Variances\",\n       subtitle = \"Notice the very different spreads\") +\n  theme_minimal()\n\np2 <- ggplot(hetero_data, aes(x = value, fill = group)) +\n  geom_density(alpha = 0.5) +\n  labs(title = \"Density Plot\", \n       subtitle = \"Different widths = different variances\") +\n  theme_minimal()\n\np1 | p2\n```\n\n::: {.cell-output-display}\n![](stat_files/figure-pdf/variance-heterogeneity-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n## Testing for Homogeneity of Variance\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(\"Testing for Equal Variances:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Testing for Equal Variances:\"\n```\n:::\n\n```{.r .cell-code}\nsep_line(\"=\", 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n================================================== \n```\n:::\n\n```{.r .cell-code}\nprint(\"Levene's Test (robust to non-normality):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Levene's Test (robust to non-normality):\"\n```\n:::\n\n```{.r .cell-code}\nlevene_test <- leveneTest(value ~ group, data = hetero_data)\nprint(levene_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value  Pr(>F)    \ngroup  2   19.13 1.3e-07 ***\n      87                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nprint(\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"\"\n```\n:::\n\n```{.r .cell-code}\nprint(\"Bartlett's Test (sensitive to non-normality):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Bartlett's Test (sensitive to non-normality):\"\n```\n:::\n\n```{.r .cell-code}\nbartlett_test <- bartlett.test(value ~ group, data = hetero_data)\nprint(bartlett_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n\n\tBartlett test of homogeneity of variances\n\ndata:  value by group\nBartlett's K-squared = 73.797, df = 2, p-value < 2.2e-16\n```\n:::\n:::\n\n\n\n::::{.callout-warning}\n## Interpreting Variance Tests\n\n**Levene's Test:** p < 0.05 indicates unequal variances (assumption violated)  \n**Bartlett's Test:** More powerful but sensitive to non-normality\n\n**What to do with unequal variances:**\n\n1. Use Welch's ANOVA instead of standard ANOVA\n2. Use Games-Howell post-hoc test instead of Tukey\n3. Consider transforming data (log, square root)\n4. Use robust methods or non-parametric alternatives\n::::\n\n## Consequences of Ignoring Unequal Variances\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standard ANOVA (assumes equal variances)\nprint(\"Standard ANOVA (assumes equal variances):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Standard ANOVA (assumes equal variances):\"\n```\n:::\n\n```{.r .cell-code}\nstandard_anova <- aov(value ~ group, data = hetero_data)\nsummary(standard_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n            Df Sum Sq Mean Sq F value Pr(>F)\ngroup        2    332   165.9   2.275  0.109\nResiduals   87   6343    72.9               \n```\n:::\n\n```{.r .cell-code}\nprint(\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"\"\n```\n:::\n\n```{.r .cell-code}\nprint(\"Welch's ANOVA (robust to unequal variances):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Welch's ANOVA (robust to unequal variances):\"\n```\n:::\n\n```{.r .cell-code}\nwelch_test <- oneway.test(value ~ group, data = hetero_data, var.equal = FALSE)\nprint(welch_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  value and group\nF = 5.2616, num df = 2.000, denom df = 42.497, p-value = 0.009086\n```\n:::\n\n```{.r .cell-code}\n# Compare p-values\ncomparison_pvalues <- data.frame(\n  Test = c(\"Standard ANOVA\", \"Welch's ANOVA\"),\n  `Assumes Equal Variances` = c(\"Yes\", \"No\"),\n  `p-value` = c(summary(standard_anova)[[1]]$`Pr(>F)`[1], welch_test$p.value),\n  Decision = c(\n    ifelse(summary(standard_anova)[[1]]$`Pr(>F)`[1] < 0.05, \"Reject H0\", \"Fail to reject H0\"),\n    ifelse(welch_test$p.value < 0.05, \"Reject H0\", \"Fail to reject H0\")\n  ),\n  check.names = FALSE\n)\n\nkable(comparison_pvalues, digits = 4,\n      caption = \"Comparison: Standard vs Welch's ANOVA with Unequal Variances\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{llrl}\n\\caption{\\label{tab:variance-consequences}Comparison: Standard vs Welch's ANOVA with Unequal Variances}\\\\\n\\toprule\nTest & Assumes Equal Variances & p-value & Decision\\\\\n\\midrule\nStandard ANOVA & Yes & 0.1088 & Fail to reject H0\\\\\nWelch's ANOVA & No & 0.0091 & Reject H0\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Part 7: Complete Analysis Pipeline\n## Step-by-Step Analysis Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalyze_data_complete <- function(data, dv, factors) {\n  formula_str <- paste(dv, \"~\", paste(factors, collapse = \" * \"))\n  formula_obj <- as.formula(formula_str)\n  \n  sep_line(\"=\", 60)\n  print(\"COMPLETE ANOVA ANALYSIS PIPELINE\")\n  sep_line(\"=\", 60)\n  \n  # 1. Check balance\n  print(\"\")\n  print(\"STEP 1: CHECKING BALANCE\")\n  sep_line(\"-\", 40)\n  design_table <- table(data[[factors[1]]], data[[factors[2]]])\n  print(design_table)\n  is_balanced <- all(design_table == design_table[1])\n  print(paste(\"Design is\", ifelse(is_balanced, \"BALANCED ✓\", \"UNBALANCED ⚠️\")))\n  \n  # 2. Fit model\n  model <- aov(formula_obj, data = data)\n  anova_table <- anova(model)\n  \n  # 3. Check assumptions\n  print(\"\")\n  print(\"STEP 2: CHECKING ASSUMPTIONS\")\n  sep_line(\"-\", 40)\n  # Normality of residuals\n  shapiro_p <- shapiro.test(residuals(model))$p.value\n  print(paste(\"Shapiro-Wilk test p =\", signif(shapiro_p, 3)))\n  # Homogeneity of variances\n  levene_p <- car::leveneTest(formula_obj, data = data)$`Pr(>F)`[1]\n  print(paste(\"Levene’s test p =\", signif(levene_p, 3)))\n  \n  # 4. Effect sizes (eta squared)\n  print(\"\")\n  print(\"STEP 3: EFFECT SIZE (η²)\")\n  sep_line(\"-\", 40)\n  ss_total <- sum(anova_table[[\"Sum Sq\"]])\n  ss_effects <- anova_table[[\"Sum Sq\"]][1:(length(factors) + 1)]\n  eta_squared <- ss_effects / ss_total\n  \n  effect_names <- rownames(anova_table)[1:(length(factors) + 1)]\n  for (i in seq_along(eta_squared)) {\n    result_text <- sprintf(\"%s: η² = %.3f \", effect_names[i], eta_squared[i])\n    if (eta_squared[i] < 0.01) {\n      result_text <- paste0(result_text, \"(negligible)\")\n    } else if (eta_squared[i] < 0.06) {\n      result_text <- paste0(result_text, \"(small)\")\n    } else if (eta_squared[i] < 0.14) {\n      result_text <- paste0(result_text, \"(medium)\")\n    } else {\n      result_text <- paste0(result_text, \"(large)\")\n    }\n    print(result_text)\n  }\n  \n  # 5. Post-hoc tests\n  print(\"\")\n  print(\"STEP 5: POST-HOC COMPARISONS\")\n  sep_line(\"-\", 40)\n  if (levene_p < 0.05) {\n    print(\"Using Games-Howell (unequal variances)\")\n    # Implement Games-Howell here if needed\n  } else {\n    print(\"Using Tukey HSD (equal variances)\")\n    if (is_balanced) {\n      print(TukeyHSD(model))\n    }\n  }\n  \n  return(invisible(model))\n}\n# Run the pipeline on unbalanced_coffee\nfinal_model <- analyze_data_complete(\n  unbalanced_coffee,\n  \"satisfaction\",\n  c(\"coffee_type\", \"time_of_day\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n============================================================ \n[1] \"COMPLETE ANOVA ANALYSIS PIPELINE\"\n============================================================ \n[1] \"\"\n[1] \"STEP 1: CHECKING BALANCE\"\n---------------------------------------- \n         \n          Afternoon Morning\n  Decaf          20      10\n  Regular        25      30\n[1] \"Design is UNBALANCED ⚠️\"\n[1] \"\"\n[1] \"STEP 2: CHECKING ASSUMPTIONS\"\n---------------------------------------- \n[1] \"Shapiro-Wilk test p = 0.15\"\n[1] \"Levene’s test p = 0.581\"\n[1] \"\"\n[1] \"STEP 3: EFFECT SIZE (η²)\"\n---------------------------------------- \n[1] \"coffee_type: η² = 0.046 (small)\"\n[1] \"time_of_day: η² = 0.053 (small)\"\n[1] \"coffee_type:time_of_day: η² = 0.425 (large)\"\n[1] \"\"\n[1] \"STEP 5: POST-HOC COMPARISONS\"\n---------------------------------------- \n[1] \"Using Tukey HSD (equal variances)\"\n```\n:::\n:::\n\n\n\n# Part 8: Practical Decision Tree\n## When to Use Which Type?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a decision guide\ndecision_guide <- data.frame(\n  Scenario = c(\n    \"Balanced design\",\n    \"Unbalanced + No interaction\",\n    \"Unbalanced + Significant interaction\",\n    \"Natural hierarchy of factors\",\n    \"Exploratory analysis\",\n    \"Following field conventions\"\n  ),\n  `Recommended Type` = c(\n    \"Any (all equal)\",\n    \"Type II\",\n    \"Type III\",\n    \"Type I\",\n    \"Type III\",\n    \"Check literature\"\n  ),\n  Reasoning = c(\n    \"All types give identical results with balanced data\",\n    \"Type II tests main effects properly without interaction assumption\",\n    \"Type III tests main effects in presence of interaction\",\n    \"Type I respects the causal/temporal order\",\n    \"Type III is most conservative\",\n    \"Some fields have established preferences\"\n  ),\n  check.names = FALSE\n)\n\nkable(decision_guide, \n      caption = \"Decision Guide for Choosing ANOVA Type\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:unnamed-chunk-3}Decision Guide for Choosing ANOVA Type}\\\\\n\\toprule\nScenario & Recommended Type & Reasoning\\\\\n\\midrule\nBalanced design & Any (all equal) & All types give identical results with balanced data\\\\\nUnbalanced + No interaction & Type II & Type II tests main effects properly without interaction assumption\\\\\nUnbalanced + Significant interaction & Type III & Type III tests main effects in presence of interaction\\\\\nNatural hierarchy of factors & Type I & Type I respects the causal/temporal order\\\\\nExploratory analysis & Type III & Type III is most conservative\\\\\n\\addlinespace\nFollowing field conventions & Check literature & Some fields have established preferences\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Part 9: Quick Reference Functions\n## Comparison Function for All Three Types\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick function to compare all three types\ncompare_anova_types <- function(formula, data, verbose = TRUE) {\n  require(car)\n  \n  # Ensure factors\n  factors <- all.vars(formula)[-1]\n  for(f in factors) {\n    if(f %in% names(data)) {\n      data[[f]] <- factor(data[[f]])\n    }\n  }\n  \n  # Check balance\n  if(length(factors) == 2) {\n    design_table <- table(data[[factors[1]]], data[[factors[2]]])\n    is_balanced <- length(unique(as.vector(design_table))) == 1\n  } else {\n    is_balanced <- FALSE\n  }\n  \n  # Type I\n  model1 <- lm(formula, data = data)\n  \n  # Type II\n  model2 <- model1\n  \n  # Type III (need sum contrasts)\n  data_type3 <- data\n  for(f in factors) {\n    if(f %in% names(data_type3)) {\n      contrasts(data_type3[[f]]) <- contr.sum(nlevels(data_type3[[f]]))\n    }\n  }\n  model3 <- lm(formula, data = data_type3)\n  \n  # Store results\n  type1_anova <- anova(model1)\n  type2_anova <- Anova(model2, type = \"II\")\n  type3_anova <- Anova(model3, type = \"III\")\n  \n  if(verbose) {\n    print(\"========== TYPE I (Sequential) ==========\")\n    print(type1_anova)\n    \n    print(\"\")\n    print(\"========== TYPE II (No Interaction) ==========\")\n    print(type2_anova)\n    \n    print(\"\")\n    print(\"========== TYPE III (Marginal) ==========\")\n    print(type3_anova)\n    \n    print(\"\")\n    print(\"========== RECOMMENDATION ==========\")\n    \n    if(is_balanced) {\n      print(\"✓ Balanced design detected - all types equivalent\")\n      print(\"→ Use Type I for computational efficiency\")\n    } else {\n      print(\"⚠️ Unbalanced design detected\")\n      \n      # Check for interaction\n      if(length(factors) == 2) {\n        # Get interaction p-value\n        interaction_term <- paste(factors, collapse = \":\")\n        if(interaction_term %in% rownames(type2_anova)) {\n          interaction_p <- type2_anova[interaction_term, \"Pr(>F)\"]\n          if(!is.na(interaction_p) && interaction_p < 0.05) {\n            print(paste(\"→ Significant interaction (p =\", round(interaction_p, 3), \")\"))\n            print(\"→ RECOMMEND: Type III for main effects interpretation\")\n          } else {\n            print(\"→ No significant interaction\")\n            print(\"→ RECOMMEND: Type II for main effects testing\")\n          }\n        }\n      }\n    }\n  }\n  \n  # Return results as a list\n  return(invisible(list(\n    type1 = type1_anova,\n    type2 = type2_anova, \n    type3 = type3_anova,\n    balanced = is_balanced\n  )))\n}\n\n# Test the function\nprint(\"Testing the comparison function with our coffee data:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"Testing the comparison function with our coffee data:\"\n```\n:::\n\n```{.r .cell-code}\nresults <- compare_anova_types(satisfaction ~ coffee_type * time_of_day, \n                              unbalanced_coffee, verbose = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.custom-output}\n[1] \"========== TYPE I (Sequential) ==========\"\nAnalysis of Variance Table\n\nResponse: satisfaction\n                        Df Sum Sq Mean Sq F value    Pr(>F)    \ncoffee_type              1  9.214   9.214  7.9036  0.006186 ** \ntime_of_day              1 10.607  10.607  9.0985  0.003417 ** \ncoffee_type:time_of_day  1 84.400  84.400 72.3995 7.439e-13 ***\nResiduals               81 94.426   1.166                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n[1] \"\"\n[1] \"========== TYPE II (No Interaction) ==========\"\nAnova Table (Type II tests)\n\nResponse: satisfaction\n                        Sum Sq Df F value    Pr(>F)    \ncoffee_type              5.339  1  4.5802  0.035352 *  \ntime_of_day             10.607  1  9.0985  0.003417 ** \ncoffee_type:time_of_day 84.400  1 72.3995 7.439e-13 ***\nResiduals               94.426 81                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n[1] \"\"\n[1] \"========== TYPE III (Marginal) ==========\"\nAnova Table (Type III tests)\n\nResponse: satisfaction\n                         Sum Sq Df   F value    Pr(>F)    \n(Intercept)             3041.77  1 2609.2756 < 2.2e-16 ***\ncoffee_type               16.40  1   14.0657 0.0003302 ***\ntime_of_day                0.01  1    0.0077 0.9302036    \ncoffee_type:time_of_day   84.40  1   72.3995 7.439e-13 ***\nResiduals                 94.43 81                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n[1] \"\"\n[1] \"========== RECOMMENDATION ==========\"\n[1] \"⚠️ Unbalanced design detected\"\n[1] \"→ Significant interaction (p = 0 )\"\n[1] \"→ RECOMMEND: Type III for main effects interpretation\"\n```\n:::\n:::\n\n\n# Part 10: Summary and Key Takeaways\n## The Essential Points\n::::{.callout-note}\n## Key Takeaways\n\n**1. ANOVA Types exist because of unbalanced designs**  \n\n- Balanced designs: All types give same results\n- Unbalanced designs: Results differ, choice matters\n\n**2. Type I (Sequential)**  \n\n- Tests each factor after those before it\n- Order matters!\n- Use when: You have a natural hierarchy\n\n**3. Type II (Hierarchical)**  \n\n- Tests main effects adjusting for other main effects\n- Assumes no interaction\n- Use when: Testing main effects, interaction not significant\n\n**4. Type III (Marginal)**  \n\n- Tests each effect adjusting for all others\n- Most conservative\n- Use when: Interaction is significant\n\n**5. Practical Advice**  \n\n- Always check assumptions first\n- Report which type you used and why\n- Consider effect sizes, not just p-values\n- Be transparent about unbalanced designs\n::::\n\n## Mathematical Summary  \n\nThe fundamental difference is in the hypotheses being tested:\n\n- **Type I (Sequential):**  \n  $H_0: \\alpha_i = 0 \\;|\\; \\mu$\n\n- **Type II (No interaction):**  \n  $H_0: \\alpha_i = 0 \\;|\\; \\mu, \\beta_j$\n\n- **Type III (Marginal):**  \n  $H_0: \\alpha_i = 0 \\;|\\; \\mu, \\beta_j, (\\alpha\\beta)_{ij}$\n\nHere, the vertical bar “$\\;|\\;$” means “given that we’ve already accounted for …”.\n\nVisual Summary of Differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a visual summary of when each type \"claims\" variance\nlibrary(ggplot2)\nlibrary(tidyr)\n\n# Create conceptual data for visualization\nvariance_allocation <- data.frame(\n  Type = rep(c(\"Type I\", \"Type II\", \"Type III\"), each = 3),\n  Component = rep(c(\"Coffee Unique\", \"Shared\", \"Time Unique\"), 3),\n  Allocation = c(\n    # Type I: Coffee gets unique + shared\n    100, 100, 0,  # Coffee tested first gets all shared\n    # Type II: Each gets only unique\n    100, 50, 100,  # Shared split conceptually\n    # Type III: Most conservative\n    100, 0, 100   # Neither gets shared\n  )\n)\n\nggplot(variance_allocation, aes(x = Component, y = Allocation, fill = Type)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Conceptual Variance Allocation by ANOVA Type\",\n       subtitle = \"How each type 'claims' variance in unbalanced designs\",\n       y = \"Variance Allocated (%)\",\n       x = \"Variance Component\") +\n  theme_minimal() +\n  scale_fill_brewer(palette = \"Set2\")\n```\n\n::: {.cell-output-display}\n![](stat_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nFinal Recommendations Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_recommendations <- data.frame(\n  `Research Question` = c(\n    \"Do factors A and B affect the outcome?\",\n    \"What is the unique contribution of A?\",\n    \"Does A matter after controlling for everything?\",\n    \"Following a causal chain A→B→C\",\n    \"Interaction is significant\"\n  ),\n  `Best Type` = c(\n    \"Type II\",\n    \"Type II\",\n    \"Type III\",\n    \"Type I\",\n    \"Type III\"\n  ),\n  `Why` = c(\n    \"Tests main effects properly without assuming interaction\",\n    \"Type II isolates unique variance of each factor\",\n    \"Type III is most conservative, controls for all\",\n    \"Type I respects the sequential nature\",\n    \"Type III tests main effects in presence of interaction\"\n  ),\n  check.names = FALSE\n)\n\nkable(final_recommendations,\n      caption = \"Final Recommendations for ANOVA Type Selection\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"))\n```\n\n::: {.cell-output-display}\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:unnamed-chunk-6}Final Recommendations for ANOVA Type Selection}\\\\\n\\toprule\nResearch Question & Best Type & Why\\\\\n\\midrule\nDo factors A and B affect the outcome? & Type II & Tests main effects properly without assuming interaction\\\\\nWhat is the unique contribution of A? & Type II & Type II isolates unique variance of each factor\\\\\nDoes A matter after controlling for everything? & Type III & Type III is most conservative, controls for all\\\\\nFollowing a causal chain A→B→C & Type I & Type I respects the sequential nature\\\\\nInteraction is significant & Type III & Type III tests main effects in presence of interaction\\\\\n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n**Remember this Above All**  \n\n::::{.callout-important}\n## The Golden Rule of ANOVA Types  \n\n**If your design is balanced, rejoice!** All types give the same answer.\n**If your design is unbalanced:**  \n\n- 1. Check if interaction is significant\n- 2. If NO interaction → Use Type II\n- 3. If YES interaction → Use Type III\n- 4. If natural hierarchy → Consider Type I\n\nAlways report: Which type you used and why!\n::::\n\n## Appendix: R Package Requirements\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Required packages for this tutorial\nrequired_packages <- c(\n  \"tidyverse\",     # Data manipulation and visualization\n  \"car\",           # For Type II and III ANOVA\n  \"emmeans\",       # Estimated marginal means\n  \"knitr\",         # For tables\n  \"kableExtra\",    # Enhanced tables\n  \"patchwork\",     # Combining plots\n  \"corrplot\",      # Correlation plots\n  \"rstatix\"        # Additional statistical tests\n)\n\n# Install if needed\ninstall.packages(required_packages)\n```\n:::",
    "supporting": [
      "stat_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}