---
title: "জীবজগতে অভিভাবকত্ব"
format: html
lang: bn
---
  
  
আমাদের পোষা গৃহপালিত প্রাণিদের মধ্যে পাখিরা ডিম থেকে বাচ্চা দেয়। যেমন, হাঁস, মুরগি, কবুতর, কোয়েল, টার্কি, টিয়া, ময়না, মুনিয়া ইত্যাদি। এরা বেশ কয়েক সপ্তাহ ধরে ডিমে তা' দিয়ে বাচ্চা ফুটায়। বন্য পরিবেশে বাস করা পাখিরাও ঠিক একইভাবে ডিম থেকেই বাচ্চা ফুটায়। এরকম একটি পাখি হল এম্পেরর পেঙ্গুইন (emperor penguin)। না, এরা গৃহপালিত নয়। এদের একমাত্র বাসস্থান একেবারে পৃথিবীর এক মেরুতে—এন্টার্কটিকায়।

পৃথিবীতে যত প্রজাতির পেঙ্গুইন আছে এরা আকারে তাদের সবার চেয়ে বড়, ওজনে সবচেয়ে ভারী। এরা মানুষের মত খাড়াভাবে হাঁটে। দূর থেকে দেখলে মনে হবে যেন কোটপরুয়া কোন ভদ্রলোক হেঁটে চলেছেন। তার ছোট ডানাজোড়ার একটা যদি একটু পাশ দিয়ে প্রসারিত করে রাখে তাহলে মনে হবে লোকটার হাতে একটা ব্রিফ কেসও আছে। কোন শীতের দেশে সে বরফ ডিঙ্গিয়ে অফিসে চলেছে। হ্যাঁ, তার অফিসের নাম দক্ষিণ মহাসাগর। সেখানে গিয়ে সে অফিসের কাজকর্ম সারে, মানে আহার খুঁজে। ক্রিল, স্কুইড, ছোট বড় বিভিন্ন মাছ খেয়ে সে পেট ভরায়। তারপর পরিবারের জন্য খাবার নিয়ে ফিরে আসে তার বাসস্থানে। কিন্তু আমরা আপাতদৃষ্টিতে হয়তো দেখব না যে সে খাবার নিয়ে ফিরেছে। আসলে খাবারটা সে নিয়ে আসে তার পাকস্থলিতে করে।

যেসব প্রাণী সমুদ্রের গভীরে খাবার খুঁজতে যায় তাদের প্রথম চ্যালেঞ্জ হল চাপ সহ্য করা। কেননা প্রতি ১০.০৬ মিটার বা ৩৩ ফুট গভীরতায় চাপ বেড়ে দ্বিগুণ হয়ে যায়। তাই তাদের হাড়ের গঠন হয় আলাদা রকম। এদের হাড়ের সংযোগস্থলে তরুনাস্থি থাকে যা চাপ সহ্য করতে সাহায্য করে। এদের হিমোগ্লোবিনের গঠনও একটু আলাদা; যেন এতো গভীরতায় অক্সিজেন পরিবহণে কোন বাধা-বিপত্তি না ঘটে। আর এদের পালকগুলো এমন যেন পানি লাগলেই তা শরীরের সাথে লেপটে যায়।

আমাদের গৃহপালিত পাখিগুলো হয় স্ত্রী-পুরুষ পালা করে ডিমে তা দেয়, কিংবা শুধু স্ত্রী পাখিই এ কাজ করে। সন্তান উৎপাদনের জন্য এদের সবচেয়ে বড় চ্যালেঞ্জ হল ডিমে তা' দেয়া। স্ত্রী এম্পেরর পেঙ্গুইন একটিমাত্র ডিম পাড়ে একেবারে শীতকালে। ডিম পাড়ার পর তাতে তা' দিয়ে ফুটানোর মত আর কোন শক্তি তার দেহে অবশিষ্ট থাকে না। তাই সে সাগরে পাড়ি জমায় খাবার খেতে। এসময় পরিবেশের তাপমাত্রা থাকে -২০ ডিগ্রি সেলসিয়াস। তাই এই ডিম থেকে বাচ্চা ফুটানো একটা বিশাল চ্যালেঞ্জ। তাহলে কি পেঙ্গুইনের বাচ্চা হবেনা? তার ধারা শেষ হয়ে যাবে? না, তখন বাকি কাজ করে পুরুষ এম্পেরর পেঙ্গুইন। ডিমকে দুই পায়ের পাতায় রেখে পেটের একটা থলিতে করে আগলে রাখে সে। তাই এসময় তারা সাধারণত যেভাবে হাঁটে সেভাবে হাঁটতেও পারে না। কিন্তু কয়দিন পরেই পরিবেশের তাপমাত্রা কমে -৬০ ডিগ্রি সেলসিয়াসে নেমে যায়। তখন কি তার শরীরের তাপমাত্রা পারবে ডিমকে ফুটানোর মত তাপ যোগাতে? আসলে কোন এম্পেরর পেঙ্গুইন বাবাই একা একা এত কম তাপমাত্রা ও প্রচন্ড বাতাসের সাথে লড়াই করে পারত না। তাই অন্য সব পুরুষ পেঙ্গুইনেরা মিলে একটা কলোনি তৈরি করে। একজন আরেকজনের সাথে গায়ে গা ঘেঁষে দাড়ায়, যেন তাপ না হারায়। আর যে পেঙ্গুইনেরা একেবারে বাহিরে পরিধির দিকে থাকে তারা শত মেইল বেগে ধেয়ে আসা ঠান্ডা বাতাস সহ্য করে। তাহলে তাদের তাপের সুষম সমাধান কিভাবে হল? আসলে তারা সবসময় গায়ে গা ঘেঁষে ঘুরতে থাকে। যারা ভিতরের দিকে ছিল তারা পরিধির দিকে আসে, আর যারা পরিধির দিকে ছিল তারা ভিতরে চলে যায়। এভাবে তারা তাপ বণ্টনের সুষ্ঠু সমাধান করে ফেলে। যেন কারো ডিম তাপের অভাবে নষ্ট না হয়। এই দীর্ঘ এক মাস তারা পৃথিবীর সবচেয়ে অন্ধকারাচ্ছন্ন ঠান্ডা আবহাওয়াকে হারিয়ে দেয় দলগত প্রচেষ্টায়।

তারপর সূর্যের দেখা মিলবার সময় হয়। আর প্রকৃতির সাথে তাল মিলিয়ে এই সময় এদের ডিম ফুটে বাচ্চা বেরিয়ে আসে। বাচ্চাটা যেহেতু অতো বেশি ঠান্ডা সহ্য করতে পারবে না তাই এই যথোপযুক্ত সময়টা খুবই গুরুত্বপূর্ণ। আর ডিমকে তা' দিতে শুরু করার দিন থেকেই পিতা পেঙ্গুইন একবেলার মাত্র আহার নিজের পাকস্থলিতে জমা করে রাখে অনাগত শিশুটির জন্য। বাচ্চা হওয়ার পর পরম আদরে সেটা বাচ্চার মুখে তুলে দেয়। এরপর শুধুই অপেক্ষা। মা ফিরে আসার অপেক্ষা। মা ফিরে আসে তার সঙ্গীর উদ্দেশ্যে ডাক ছেড়ে। পরস্পরের ডাক শুনে এভাবেই তারা একে অপরকে চিনে নেয়। বাবা তখন তার আদরের ছানাকে মায়ের দায়িত্বে দিয়ে দেয়। ৪ মাসের দীর্ঘ লড়াইয়ের পর বাচ্চার মুখ দেখা স্নেহবাৎসল বাবা অতোটা সহজে সন্তানকে ছাড়তে চায়না। তবু, ক্ষুধার চেয়ে কঠিন কিছু মনে হয় নেই! মাকে সন্তান লালন-পালনের দায়িত্ব দিয়ে বাবা তখন সাগরে যায় খাবার খেতে। কেননা সে দীর্ঘ ৪ মাস ধরে কোন খাবারই খায়নি! আর মা যদি ফিরে না আসে, যদি শিকারী প্রাণীর হাতে ধরা পড়ে, কিংবা যদি খাড়া ঢাল থেকে পড়ে মারা যায় তাহলে ভবিষ্যত অনিশ্চিত। বাবাকে বেঁচে থাকার জন্য যেতেই হবে সাগরে। বাচ্চাটা তখন অন্য সব মায়েদের কাছে যায় খাবারের জন্য। কিন্তু তাদের তো পরিবার আছে, তারা আর কাউকে সহ্য করেনা। আর মা যদি এসে দেখে যে তার ডিমটি ফু্টে নি কিংবা ছোট্ট ছানাটি মরে গেছে তাহলে মায়ের আর কষ্ট দেখে কে! যেসব বাচ্চার মা নাই তাদেরকে দত্তক নেয়ার জন্য তারা উঠেপড়ে লাগে, অন্য সন্তানহারা মায়েদের সাথে প্রতিযোগিতা শুরু করে দেয় তারা। এতে করে অনেক সময় বাচ্চা প্রাণ হারায় ওইসব প্রতিযোগী মায়েদের প্রচণ্ড মাতৃত্ববোধের চাপে।

জীবজগতে সব প্রাণিদেরই বাবা-মা যেমন আছে, ঠিক তেমনি আছে সন্তানের প্রতি মা-বাবার স্নেহ-ভালবাসা, আদর-যত্ন এবং মঙ্গলচিন্তা। সন্তানেরও আত্মচিন্তার উর্ধ্বে ভালবাসা ও মঙ্গলাকাঙ্ক্ষা আছে মা-বাবা কিংবা পরিবার নিয়ে, তবে সেটা আসবে অনেক পরে। শৈশবে পিতা-মাতার প্রতি সন্তানের ভালবাসা মনে হয় সবচেয়ে আত্মকেন্দ্রিক--বেঁচে থাকার তাগিদে। আর মা-বাবা তাদের উপর সন্তানের এই নির্ভরশীলতার মধ্য দিয়ে বুনতে থাকেন সন্তানের মধ্য দিয়ে নিজেকে অমর করে রেখে যাবার সুপ্তবাসনা। শুধু যে মানুষের মধ্যেই এসব ব্যাপার আছে তা কিন্তু নয়। আবার অন্যান্য জীবে এই ব্যাপারগুলো আছে বলে মানুষের এই দিকগুলো কোনভাবে খাটো হয়েছে এমনটাও নয়। ঠিক তেমনিভাবে তাদের অভিভাবকত্ব বা সন্তান বাৎসল্যকেও ছোট করে দেখবার কোন উপায় নেই। সন্তান তো সন্তানই, মা-বাবা তো মা-বাবাই। এর কোন জাতিভেদ চলে না। এ যেন একে অপরকে জানতে পারার, বুঝতে পারার জন্য বিধাতার এক অন্তর্নিহিত নিদর্শন। আমাদের বুঝতে হবে, খুঁজে নিতে হবে সেগুলো।।

[← Back to all Bangla Blogs](index.qmd)
