---
title: "এক বিধবার গল্প"
format: html
lang: bn
---
  
<style>
  .content {
    text-align: justify !important;
  }
  p {
    text-align: justify !important;
  }
  .quarto-body {
    text-align: justify !important;
  }
</style>
  
নাম তার *Alium sativum*। খালাত বোন *Alium cepa*-র সাথে তার অনেক মিল। তাই তারা একই ফ্যামিলিতে আছে। অবশ্য অমিলও আছে অনেক। *Alium sativum* এর গায়ে সেই আজন্ম বাল্যবৈধব্যের সাজ, আর *Alium cepa*-র লাল টুকটুকে বিয়ের সাজ আজও ঘোচে নি।

আজ থেকে প্রায় ২-৩ বছর আগে, একদিন দেখি আমার ছোট বোন এক আঁটি ফুল (flower stalk) নিয়ে আসছে। মনে হল পিয়াজের। কিন্তু কাছে আসতে মনে হল— না, ওগুলো রসুনের হবে। রসুন রসুন গন্ধ বেরুচ্ছে। তবু জিজ্ঞাসা করলাম, “ওগুলো কি?” সে বলল, “রসুনের ঢেঁপ।” হাতে নিয়ে অবাক হয়ে দেখতে লাগলাম। জিবনের এতোগুলো বছর পাড়ি দিলাম, গ্রামেই বাস, ফসলের মাঠের সাথে লুটোপুটি খেতে খেতে বড় হলাম, অথচ রসুনের ফুলই আমি দেখি নি এর আগে!!! দেখলাম কিছু পুষ্পদন্ড ( scape বা ঢেঁপ) কিছুটা প্যাঁচানো, আর কিছু সোজা। আসলে কিছুটা প্যাঁচানোগুলো ছিল বেশি কচি, আর সোজাগুলো ছিল একটু ম্যাচিউর। যখন আরো ভাল করে দেখতে লাগলাম আমার তো চোখ চড়ক গাছ হবার পালা। একি! এর umbel বা ক্যাপসুলের ভিতরে দেখি ছোট ছোট রসুনের কোয়া!!! বাহ্, মাটির নিচেও রসুন, বাতাসেও রসুন, ভাল না?? Umbel এর ভিতরের এই কোয়াগুলোকে বলে bulbils। আর মাটির নিচেরগুলোকে বলে cloves। Clove-গুলো মিলে গঠন করে bulb (বাতি)। আসলে দেখতে বাতির মত বলেই এর নাম হয়েছে bulb. এই bulb আর bulbils দিয়ে রসুনের অঙ্গজ জনন ঘটে। রসুনের umbel এর ভিতরে আবার অনেক ফুলও আছে। আসলে রসুনের inflorescence (পুষ্পবিন্যাস) এর নিচের দিকটা তৈরি করে bulbils, আর উপরের দিকটা হয়ে যায় ফুল। যাই হোক, আমি এতোদিন রসুনের এই রূপের কিছুই দেখি নি। শুধু মায়ের হাতের রান্নায় রসুনের ব্যবহার দেখেছি। জ্বর হলে ওষুধের সাথে সাথে চাল ভাজা, মরিচ, আদা, রসুনের ঝাল চাটনি খেয়ে ফোঁপাতে ফোঁপাতে জ্বর সারার আশা করেছি। রসুনের গন্ধযুক্ত নিঃশ্বাস (garlic breath) ছেড়েছি—- হরেক রকম ফুলও আমি দেখেছি, অস্বীকার করছি না— কিন্তু রসুনের ফুল আমি এর আগে দেখি নি।

আমি যেমন রসুনের ফুলের ব্যাপারে ছিলাম লাওয়াকিফ, ঠিক তেমনি আগে ভাবা হত এর ফুল sterile (বন্ধ্যা)। কিন্তু এগুলো আসলে বন্ধ্যা নয়। ১৮৭৫ সালে Eduard Regel সর্বপ্রথম রসুনের এই অনন্য ফুলধারণ পদ্ধতির বর্ণনা দেন।

এখন তাহলে আমরা বলতেই পারি রসুনের প্রজননের মাধ্যম কয়টি। বলুন তো কি কি? হ্যাঁ, cloves, bulbils আর বীজ। তাহলে শুধু cloves দিয়ে আমাদের দেশের কৃষকেরা চাষ করে কেন এই প্রশ্নটা আপনাদের মনে জাগতে পারে। আমারও জেগেছিল। এর সহজ উত্তর হচ্ছে বীজ ও bulbils এর কন্ট্রোলিং, আবাদ করা বেশ ঝক্কির ব্যাপার।তাছাড়া এগুলো থেকে রসুন পেতে লেগে যাবে অনেক বেশি সময়, শ্রমও লাগবে বেশি। অর্থ উপার্জন, দেশভর্তি মানুষের চাহিদা মেটানো যেখানে কৃষকদের প্রধান ও প্রথম লক্ষ্য সেখানে এমন সময় ও শ্রমসাপেক্ষ কাজ করা নিশ্চই কৃষকদের কাজ নয়। তবুও প্রশ্ন থেকেই যায় bulbils বা বীজ দিয়ে কী আবাদ করার দরকার পড়বে কখনো?

হ্যাঁ, এর উত্তরটা অনেক important. রসুন প্রজাতীর স্বকীয়তা রক্ষা করা, জাত উন্নয়ন, বংশনাশের হাত থেকে রক্ষা করা সবকিছুর সমাধান দেবে এই উত্তরটিই।

যদিও রসুন স্বাভাবিকভাবেই অযৌন জনন প্রক্রিয়ায় (bulb বা bulbils দিয়ে) বংশ বৃদ্ধি করে, বীজ উৎপাদন হার ও অঙ্কুরোদগম হার অনেক কম তবুও আমরা যদি বীজ পাবার জন্য চাষ করতে শুরু করি ধীরে ধীরে বীজ উৎপাদন হার বাড়তে থাকবে। অযৌন বা অঙ্গজ জনন পদ্ধতি মাতৃ উদ্ভিদের হুবহু কপি (clone) তৈরি করে। অর্থাৎ, কোনো গাছের যা বৈশিষ্ট্য, অঙ্গজ প্রজননের মাধ্যমে পাওয়া গাছেরও ঠিক একই বৈশিষ্ট্য হবে। কাজেই যদি মিউটেশন বা ভাইরাল ইনফেকশনের কারণে কোনো ক্ষতিকর বৈশিষ্ট্যের আগমন ঘটে তাহলে সেটাও যতবার এই পদ্ধতিতে আবাদ করবেন ততবারই বাহিত হবে। এতে হয়তো একটা নির্দিষ্ট এলাকায় (পরিসর অনেক বড়ও হতে পারে) রসুনের চাষই হয়তো বন্ধ হয়ে যাবে। অবশ্য umbel এর ভিতরে সুরক্ষিত থাকায় bulbils এ এই ধরণের পরিবর্তন খুব কমই হয়। তবু চান্স তো থেকেই যায়। কিন্তু বীজ দিয়ে চাষ করলে এই সম্ভাবনা আমরা এড়াতে পারি। কেননা দেহকোষের মিউটেশনের প্রভাব বীজে বাহিত হয় না। কাজেই আমরা যদি হুমকির হাত থেকে রসুনকে বাঁচাতে চাই, সহজেই জাত উন্নয়ন করতে চাই (hybridization বা crossing এর মাধ্যমে), কিংবা যদি নিদেনপক্ষে এর চমৎকার ফুলধারণ দেখে মন জুড়াতে চাই, তাহলে আসুন সেটা কীভাবে করা যায় দেখে নিই। বাগানের একখন্ড জমিতে রসুনের cloves লাগিয়ে ফেলুন। জায়গার অভাব থাকলে টবে কিংবা ছাদে মাটি দিয়ে কাজটা করে ফেলুন।

জাত উন্নয়ন বা হাইব্রিডাইজেশনের জন্য প্যারেন্ট উদ্ভিতের অন্তত একটা নির্দিষ্ট এলাকায় খুব ভালভাবে বেঁচে থাকার সক্ষমতা (adaptability) থাকতে হবে, বীজ দিয়ে বংশবৃদ্ধি করা গাছগুলোর বেঁচে থাকতে হবে। কিন্তু রসুনের তা খুবই কম। তাই আগে রসুনের এই adaptability নিয়ে আসার জন্য বেশ কিছু প্রজন্ম ধরে বীজ দিয়ে চাষ করতে থাকতে হবে।

রসুনের ফুল protandrous ধরণের, অর্থাৎ এর stigma (গর্ভমুন্ড) পরাগগ্রাহী (receptive) হবার আগেই পরাগরেণু (pollen grain) ম্যাচিউর হয়ে যায়। তাই এদের স্বনিষেক (self-fertilization) ঘটে না। তবে একই umbel এর অন্যান্য ফুলকে নিষিক্ত করতে পারে। মৌমাছির মত অন্যান্য কীটপতঙ্গেরা এতে সাহায্য করে ফুলে ফুলে ঘুরে মধু আহরণের চারিত্রিক বৈশিষ্ট্য দিয়ে। রসুনের গর্ভাশয়ে থাকে তিনটি seed chamber. প্রতি চ্যাম্বারে আছে দুইটি করে ডিম্বক (ovule— যা বীজে পরিণত হয়।). সুতরাং, রসুনের একটি ফুল থেকেই আমরা পেয়ে যাব ছয়টি বীজ। প্রতি umbel থেকে কয়েক শ’।

এখন সমস্যা হচ্ছে ফুল ও bulbils পুষ্টি পাবার লড়াইয়ে নামে। প্রাকৃতিকভাবে bulbils-ই জেতে। তাই বীজ পেতে চাইলে আগে এদেরকে ছাড়ানো দরকার। ভ্যারিটিভেদে bulbils এর সংখ্যা ও প্রকৃতির তারতম্য আছে। সংখ্যা কম ও আকারে বড় হলে ছাড়ানোটা সহজ হয়। তবে সংখ্যায় বেশি ও আকারে ছোট হলে প্রথমে বাইরের দিকেরগুলো ছাড়িয়ে নিয়ে কয়েকদিন পর ভিতরের দিকেরগুলো ছাড়াতে হবে। নজর রাখতে হবে যেন ফুলের কোনো ক্ষতি না হয়। আমাদের দেশে যেগুলো চাষ হয় সেগুলোতে bulbils এর সংখ্যা কম আর আকারেও বড়। কাজেই কাজটা সহজই হবে। পানি, সার ও পরিচর্যা অব্যাহত রাখতে হবে। পরাগায়ন হবার ৪৫-৬০ দিনের মধ্যেই বীজ পরিপক্ব হয়ে যায়। বীজ পরিপক্ব হবার আগেই যদি গাছ বুড়িয়ে যায় তাহলে scape টা কেটে নিয়ে পানিতে ডুবিয়ে রাখতে হবে— পাতাবাহারের ডালকে যেভাবে বাঁচিয়ে রাখা হয়, ঠিক সেভাবেই।তাহলেই আপনি বীজ পেয়ে যাবেন। এরপর এভাবে বীজ উৎপাদনের মাধ্যমে উপর্যুপরি আবাদ করতে থাকলে একটা অভিযোজিত (well adapted) ভ্যারিটি পেয়ে যাব আমরা। এরপর ক্রসিং বা হাইব্রিডাইজেশনের বিভিন্ন টেকনিক কাজে লাগিয়ে আমরা পেয়ে যাব অনেক উন্নত জাত। আর এই উন্নত জাতগুলোরও তো bulb, bulbils থাকবেই, এদের দিয়ে আমরা প্রতিটি নতুন জাত বা ভ্যারিটিকে সংরক্ষণ করতে পারি। যৌন জননের পাশাপাশি অঙ্গজ বা অযৌন জনন থাকার এটাই এক বিশাল সুবিধা। কাজেই আসুন আমরা নতুনভাবে প্রকৃতিটাকে দেখতে শুরু করি। একবীজপত্রী ও দ্বিবীজপত্রী উদ্ভিদের অযৌন ও যৌন জনন পদ্ধতিগুলো নিয়ে ভাবতে থাকি।পদ্ধতিগুলোর পার্থক্যগুলোও ভাবতে থাকি। পথ চলতে চলতে যে গাছগুলো চোখে পড়ে সেগুলোর কান্ড, পাতা, ফুল, ফলের মিল-অমিলগুলো নিয়ে ভাবতে থাকি। তাহলেই উদ্ভিদবিদ্যা জানার উৎসাহ-উদ্দীপনা, আনন্দ দ্বিগুণ হয়ে যাবে বলে আমি মন করি।

[← Back to all Bangla Blogs](index.qmd)
